export const trendOfferLanes = [
  {
    "slug": "ai-note-takers",
    "title": "AI note takers and meeting assistants",
    "seed": "AI note taker",
    "audience": "students, sales teams, recruiters, agencies, founders",
    "offer": "AI meeting note taker short list + AI Tool Stack Quiz",
    "monetize": "SaaS affiliate/referral, setup audit, newsletter opt-in",
    "risk": "low",
    "cta": "Get the AI stack quiz",
    "href": "/ai-tool-stack-quiz.html",
    "momentumPct": 67,
    "latest": 60,
    "queries": [
      "pocket",
      "pocket ai",
      "cluely",
      "turboai",
      "bluedot ai note taker",
      "bluedot",
      "bluedot ai",
      "plaud"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "portable-power-stations",
    "title": "Portable power stations and solar generators",
    "seed": "portable power station",
    "audience": "apartment dwellers, road trippers, storm prep buyers",
    "offer": "Backup power starter kit + Amazon manual links",
    "monetize": "Amazon Associates manual links, direct brand programs, preparedness checklist opt-in",
    "risk": "medium",
    "cta": "Join the power-prep list",
    "href": "/trends/portable-power-stations.html",
    "momentumPct": 403,
    "latest": 27,
    "queries": [
      "anker solix c1000 gen 2 portable power station",
      "anker solix c2000 gen 2 portable power station",
      "jackery explorer 1500 ultra portable power station",
      "ecoflow delta 3 portable power station",
      "anker solix",
      "portable power station reviews",
      "bluetti portable power station",
      "anker portable power station"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "home-wellness-gadgets",
    "title": "Home wellness gadgets: red light, sauna, air quality",
    "seed": "red light therapy",
    "audience": "wellness shoppers, home office buyers, gift buyers",
    "offer": "At-home wellness gadget guide",
    "monetize": "Amazon/manual affiliate, retailer affiliate, weekly picks",
    "risk": "medium",
    "cta": "Get wellness picks",
    "href": "/trends/home-wellness-gadgets.html",
    "momentumPct": 141,
    "latest": 58,
    "queries": [
      "clara red light therapy mask",
      "ihome red light therapy mask",
      "inia red light mask",
      "red light therapy mask shark",
      "shark red light mask",
      "red light therapy panel",
      "red light panel",
      "red light therapy for body"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "air-purifiers",
    "title": "Air purifiers and small-space air quality",
    "seed": "air purifier",
    "audience": "pet owners, renters, parents, bedroom/home office shoppers",
    "offer": "Air purifier finder for bedrooms, pets, and apartments",
    "monetize": "Amazon Associates manual links, retailer direct programs",
    "risk": "medium",
    "cta": "See air-quality picks",
    "href": "/trends/air-purifiers.html",
    "momentumPct": 302,
    "latest": 45,
    "queries": [
      "dyson hushjet compact air purifier",
      "portable air purifier",
      "car air purifier",
      "miko air purifier",
      "ikea air purifier",
      "coway airmega",
      "shark neverchange air purifier",
      "blue air purifier"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "walking-pad-desk",
    "title": "Walking pads, standing desks, and compact home office",
    "seed": "walking pad",
    "audience": "remote workers, creators, operators, small apartment buyers",
    "offer": "Small-space office movement setup",
    "monetize": "Amazon/manual links, office furniture affiliates, setup checklist",
    "risk": "low",
    "cta": "Get the home-office checklist",
    "href": "/trends/walking-pad-desk.html",
    "momentumPct": 158,
    "latest": 48,
    "queries": [
      "overself walking pad",
      "compact walking pad",
      "portable walking pad",
      "walking pad for under desk",
      "pink walking pad",
      "walking pad with desk",
      "mini walking pad",
      "walking pad for desk"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "meal-prep-starter-kit",
    "title": "Meal prep containers and protein snack kits",
    "seed": "meal prep containers",
    "audience": "busy workers, students, families, budget shoppers",
    "offer": "Meal prep starter kit and snack finder",
    "monetize": "Amazon/manual links, grocery/coupon partners, checklist signup",
    "risk": "medium",
    "cta": "Get meal-prep picks",
    "href": "/trends/meal-prep-starter-kit.html",
    "momentumPct": 193,
    "latest": 34,
    "queries": [
      "cooking for gains",
      "lidl near me",
      "best meal prep containers",
      "best containers for meal prep",
      "containers for meal prep",
      "glass containers",
      "food prep containers",
      "meal prep food containers"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "pet-tech-safety",
    "title": "Pet tech: GPS trackers, cameras, and travel safety",
    "seed": "dog GPS tracker",
    "audience": "dog owners, travelers, apartment pet owners",
    "offer": "Pet safety tech starter kit",
    "monetize": "Amazon/manual links, pet retailer affiliates, direct programs",
    "risk": "medium",
    "cta": "Get pet-tech picks",
    "href": "/trends/pet-tech-safety.html",
    "momentumPct": 338,
    "latest": 28,
    "queries": [
      "itagpro",
      "optimus 3.0 gps tracker",
      "vyncs gps tracker",
      "mini gps tracker",
      "gps tracker for car",
      "gps tracker for dog",
      "pet gps tracker",
      "dog collar gps tracker"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "robot-vacuums-smart-home",
    "title": "Robot vacuums and smart-home helpers",
    "seed": "robot vacuum",
    "audience": "busy families, pet owners, renters, smart-home buyers",
    "offer": "Robot vacuum and smart apartment guide",
    "monetize": "Amazon/manual links, smart-home affiliate programs",
    "risk": "low",
    "cta": "See smart-home picks",
    "href": "/trends/robot-vacuums-smart-home.html",
    "momentumPct": 339,
    "latest": 37,
    "queries": [
      "irobot roomba 104 robot vacuum & mop",
      "shark stratos 2-in-1 robot vacuum & mop",
      "irobot roomba 960 wi-fi connected robot vacuum",
      "irobot roomba 980 robot vacuum",
      "best robot vacuum 2025",
      "irobot",
      "dreame robot vacuum",
      "roomba"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "travel-tech-esim",
    "title": "Travel tech: eSIMs, backpacks, and compact gear",
    "seed": "eSIM travel",
    "audience": "travelers, digital nomads, families, remote workers",
    "offer": "Travel tech checklist and eSIM guide",
    "monetize": "eSIM affiliate programs, travel gear manual links, checklist opt-in",
    "risk": "low",
    "cta": "Get travel-tech picks",
    "href": "/trends/travel-tech-esim.html",
    "momentumPct": 134,
    "latest": 36,
    "queries": [
      "ai news today",
      "openai news today",
      "journey japan esim",
      "what is esim",
      "holafly",
      "holafly esim",
      "uk esim",
      "esim uk travel"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "sleep-beauty-microtrends",
    "title": "Sleep and beauty microtrends",
    "seed": "sleep bonnet",
    "audience": "beauty shoppers, gift buyers, sleep-routine optimizers",
    "offer": "Low-lift sleep and beauty finds",
    "monetize": "Amazon/manual links, beauty retailer programs, weekly picks",
    "risk": "medium",
    "cta": "Get sleep/beauty picks",
    "href": "/trends/sleep-beauty-microtrends.html",
    "momentumPct": 70,
    "latest": 47,
    "queries": [
      "mulberry silk",
      "mulberry silk bonnet",
      "satin sleep cap",
      "satin sleep bonnet",
      "satin bonnet",
      "hair bonnet",
      "silk bonnet",
      "bonnet for hair"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  },
  {
    "slug": "weekend-hobby-kits",
    "title": "Weekend hobby kits: indoor gardens, sourdough, pickleball",
    "seed": "indoor garden kit",
    "audience": "gift buyers, hobby starters, families, weekend project shoppers",
    "offer": "Weekend hobby starter-kit guide",
    "monetize": "Amazon/manual links, retail affiliate programs, gift guide signup",
    "risk": "low",
    "cta": "Get hobby picks",
    "href": "/trends/weekend-hobby-kits.html",
    "momentumPct": 1629,
    "latest": 16,
    "queries": [
      "click & grow smart garden 3",
      "indoor smart herb garden kit",
      "herb garden kit",
      "indoor herb garden kit",
      "indoor herb garden",
      "indoor garden kit with light",
      "indoor garden system",
      "hydroponic garden"
    ],
    "trendUpdatedAt": "2026-05-15T20:09:40.014Z"
  }
];
