export const trendOfferLanes = [
  {
    "slug": "ai-note-takers",
    "title": "AI note takers and meeting assistants",
    "seed": "AI note taker",
    "audience": "students, sales teams, recruiters, agencies, founders",
    "offer": "AI meeting note taker short list + AI Tool Stack Quiz",
    "monetize": "SaaS affiliate/referral, setup audit, newsletter opt-in",
    "risk": "low",
    "cta": "Get the AI stack quiz",
    "href": "/ai-tool-stack-quiz.html",
    "momentumPct": 61,
    "latest": 57,
    "queries": [
      "pocket ai",
      "plaud note pro",
      "notee",
      "cluely ai",
      "bluedot ai",
      "pocket",
      "bluedot ai note taker",
      "bluedot"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "portable-power-stations",
    "title": "Portable power stations and solar generators",
    "seed": "portable power station",
    "audience": "apartment dwellers, road trippers, storm prep buyers",
    "offer": "Backup power starter kit + Amazon manual links",
    "monetize": "Amazon Associates manual links, direct brand programs, preparedness checklist opt-in",
    "risk": "medium",
    "cta": "Join the power-prep list",
    "href": "/trends/portable-power-stations.html",
    "momentumPct": 397,
    "latest": 27,
    "queries": [
      "anker solix c2000 gen 2 portable power station",
      "jackery explorer 1500 ultra portable power station",
      "ecoflow delta 3 portable power station",
      "anker solix",
      "portable power station reviews",
      "anker portable power station",
      "anker power station",
      "anker"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "home-wellness-gadgets",
    "title": "Home wellness gadgets: red light, sauna, air quality",
    "seed": "red light therapy",
    "audience": "wellness shoppers, home office buyers, gift buyers",
    "offer": "At-home wellness gadget guide",
    "monetize": "Amazon/manual affiliate, retailer affiliate, weekly picks",
    "risk": "medium",
    "cta": "Get wellness picks",
    "href": "/trends/home-wellness-gadgets.html",
    "momentumPct": 123,
    "latest": 58,
    "queries": [
      "clara red light therapy mask",
      "ihome red light therapy mask",
      "shark cryoglow mask",
      "red light therapy for hearing loss",
      "inia red light mask",
      "red light therapy mask shark",
      "red light panel therapy",
      "red light panel"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "air-purifiers",
    "title": "Air purifiers and small-space air quality",
    "seed": "air purifier",
    "audience": "pet owners, renters, parents, bedroom/home office shoppers",
    "offer": "Air purifier finder for bedrooms, pets, and apartments",
    "monetize": "Amazon Associates manual links, retailer direct programs",
    "risk": "medium",
    "cta": "See air-quality picks",
    "href": "/trends/air-purifiers.html",
    "momentumPct": 283,
    "latest": 40,
    "queries": [
      "dyson hushjet compact air purifier",
      "portable air purifier",
      "miko air purifier",
      "car air purifier",
      "coway airmega",
      "austin air purifier",
      "shark neverchange air purifier",
      "blue air purifier"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "walking-pad-desk",
    "title": "Walking pads, standing desks, and compact home office",
    "seed": "walking pad",
    "audience": "remote workers, creators, operators, small apartment buyers",
    "offer": "Small-space office movement setup",
    "monetize": "Amazon/manual links, office furniture affiliates, setup checklist",
    "risk": "low",
    "cta": "Get the home-office checklist",
    "href": "/trends/walking-pad-desk.html",
    "momentumPct": 149,
    "latest": 42,
    "queries": [
      "overself walking pad",
      "compact treadmill",
      "compact walking pad",
      "mini treadmill",
      "portable walking pad",
      "walking pad for under desk",
      "walking pad with desk",
      "under desk treadmill"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "meal-prep-starter-kit",
    "title": "Meal prep containers and protein snack kits",
    "seed": "meal prep containers",
    "audience": "busy workers, students, families, budget shoppers",
    "offer": "Meal prep starter kit and snack finder",
    "monetize": "Amazon/manual links, grocery/coupon partners, checklist signup",
    "risk": "medium",
    "cta": "Get meal-prep picks",
    "href": "/trends/meal-prep-starter-kit.html",
    "momentumPct": 196,
    "latest": 34,
    "queries": [
      "cooking for gains",
      "cooking for gains meal prep containers",
      "lidl near me",
      "best meal prep containers",
      "best containers for meal prep",
      "containers for meal prep",
      "meal prep containers glass",
      "glass meal prep"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "pet-tech-safety",
    "title": "Pet tech: GPS trackers, cameras, and travel safety",
    "seed": "dog GPS tracker",
    "audience": "dog owners, travelers, apartment pet owners",
    "offer": "Pet safety tech starter kit",
    "monetize": "Amazon/manual links, pet retailer affiliates, direct programs",
    "risk": "medium",
    "cta": "Get pet-tech picks",
    "href": "/trends/pet-tech-safety.html",
    "momentumPct": 378,
    "latest": 28,
    "queries": [
      "optimus gps tracker",
      "itagpro",
      "vyncs gps tracker",
      "mini gps tracker",
      "gps tracker for dog",
      "gps for dog",
      "pet gps tracker",
      "tractive gps"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "robot-vacuums-smart-home",
    "title": "Robot vacuums and smart-home helpers",
    "seed": "robot vacuum",
    "audience": "busy families, pet owners, renters, smart-home buyers",
    "offer": "Robot vacuum and smart apartment guide",
    "monetize": "Amazon/manual links, smart-home affiliate programs",
    "risk": "low",
    "cta": "See smart-home picks",
    "href": "/trends/robot-vacuums-smart-home.html",
    "momentumPct": 338,
    "latest": 34,
    "queries": [
      "irobot roomba 104 robot vacuum & mop",
      "shark stratos 2-in-1 robot vacuum & mop",
      "irobot roomba 960 wi-fi connected robot vacuum",
      "irobot roomba 980 robot vacuum",
      "best robot vacuum 2025",
      "irobot",
      "dreame robot vacuum",
      "roomba"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "travel-tech-esim",
    "title": "Travel tech: eSIMs, backpacks, and compact gear",
    "seed": "eSIM travel",
    "audience": "travelers, digital nomads, families, remote workers",
    "offer": "Travel tech checklist and eSIM guide",
    "monetize": "eSIM affiliate programs, travel gear manual links, checklist opt-in",
    "risk": "low",
    "cta": "Get travel-tech picks",
    "href": "/trends/travel-tech-esim.html",
    "momentumPct": 132,
    "latest": 36,
    "queries": [
      "travel news today",
      "ai news today",
      "openai news today",
      "journey japan esim",
      "what is esim",
      "esim china",
      "holafly",
      "holafly esim"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "sleep-beauty-microtrends",
    "title": "Sleep and beauty microtrends",
    "seed": "sleep bonnet",
    "audience": "beauty shoppers, gift buyers, sleep-routine optimizers",
    "offer": "Low-lift sleep and beauty finds",
    "monetize": "Amazon/manual links, beauty retailer programs, weekly picks",
    "risk": "medium",
    "cta": "Get sleep/beauty picks",
    "href": "/trends/sleep-beauty-microtrends.html",
    "momentumPct": 65,
    "latest": 46,
    "queries": [
      "mulberry silk bonnet",
      "satin sleep cap",
      "satin bonnet for sleep",
      "hair bonnet",
      "silk bonnet",
      "bonnet for hair",
      "satin sleep bonnet",
      "satin bonnet"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  },
  {
    "slug": "weekend-hobby-kits",
    "title": "Weekend hobby kits: indoor gardens, sourdough, pickleball",
    "seed": "indoor garden kit",
    "audience": "gift buyers, hobby starters, families, weekend project shoppers",
    "offer": "Weekend hobby starter-kit guide",
    "monetize": "Amazon/manual links, retail affiliate programs, gift guide signup",
    "risk": "low",
    "cta": "Get hobby picks",
    "href": "/trends/weekend-hobby-kits.html",
    "momentumPct": 2400,
    "latest": 18,
    "queries": [
      "click & grow smart garden 3",
      "indoor smart herb garden kit",
      "herb indoor garden kit",
      "indoor herb garden",
      "herb garden kit",
      "indoor garden kit with light",
      "indoor garden system",
      "hydroponic garden"
    ],
    "trendUpdatedAt": "2026-05-16T21:36:43.694Z"
  }
];
