-- StuffPrettyGood Amazon offer inventory + image-rights seed schema
-- Task: t_51c156c8
-- Status: additive migration draft for LeadFS/WebDev/ComplyOps review before production use.
-- Safety: no raw secrets, no raw PII, no copied Amazon images/prices/ratings/reviews/availability.

create extension if not exists pgcrypto;

create table if not exists amazon_offer_inventory (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  category text not null,
  amazon_query text not null,
  amazon_search_url text generated always as ('https://www.amazon.com/s?k=' || replace(amazon_query, ' ', '+') || '&tag=mehyarmedia-20') stored,
  store_id_tag_ref text not null default 'mehyarmedia-20',
  image_url text,
  image_source text not null default 'none_selected_amazon_images_prohibited_until_rights_approved',
  image_license text not null default 'not_applicable',
  image_status text not null default 'needs_owned_or_generated_asset',
  generated_original_fallback_asset jsonb not null default '{}',
  best_for text[] not null default '{}',
  buyer_criteria text not null,
  risk_level text not null default 'medium' check (risk_level in ('low','medium','high','blocked')),
  risk_notes text,
  last_checked date not null default current_date,
  approval_state text not null default 'data_seed_ready_compliance_review_required',
  publish_state text not null default 'hold_for_webdev_generation_and_compliance_gate',
  offers_path text not null,
  go_path text not null,
  click_count bigint not null default 0,
  signup_count bigint not null default 0,
  source_attribution jsonb not null default '{}',
  score numeric check (score between 0 and 100),
  confidence numeric check (confidence between 0 and 1),
  scoring_inputs jsonb not null default '{}',
  scoring_weights jsonb not null default '{"buyer_intent":0.25,"amazon_fit":0.20,"content_monetization_fit":0.20,"rights_readiness":0.15,"risk_penalty":0.10,"category_coverage":0.10}',
  missing_data text[] not null default '{}',
  false_positive_risks text[] not null default '{}',
  raw_pii_stored boolean not null default false,
  raw_secret_stored boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint amazon_offer_inventory_slug_paths check (
    slug ~ '^[a-z0-9][a-z0-9-]{2,120}$'
    and offers_path = '/offers/' || slug
    and go_path = '/go/' || slug
  ),
  constraint amazon_offer_inventory_tag_reference_only check (store_id_tag_ref = 'mehyarmedia-20'),
  constraint amazon_offer_inventory_no_raw_pii_or_secret check (raw_pii_stored = false and raw_secret_stored = false),
  constraint amazon_offer_inventory_no_unapproved_amazon_images check (
    image_status <> 'approved'
    or image_source in ('owned','generated','licensed_stock','public_domain','merchant_provided_with_written_rights')
  ),
  constraint amazon_offer_inventory_publish_gate check (
    publish_state not in ('publish_ready','published')
    or (
      approval_state = 'approved_for_public_publish'
      and image_status = 'approved'
      and image_source in ('owned','generated','licensed_stock','public_domain','merchant_provided_with_written_rights')
      and source_attribution <> '{}'::jsonb
      and risk_level <> 'blocked'
    )
  )
);

create index if not exists amazon_offer_inventory_category_idx on amazon_offer_inventory(category, risk_level, approval_state);
create index if not exists amazon_offer_inventory_publish_idx on amazon_offer_inventory(publish_state, approval_state, image_status);

create or replace view amazon_offer_inventory_public_ready as
select
  slug,
  title,
  category,
  amazon_query,
  store_id_tag_ref,
  offers_path as public_landing_url,
  go_path as redirect_url,
  image_url,
  image_source,
  image_license,
  image_status,
  generated_original_fallback_asset,
  best_for,
  buyer_criteria,
  risk_level,
  last_checked,
  click_count,
  signup_count,
  source_attribution,
  score,
  confidence
from amazon_offer_inventory
where approval_state = 'approved_for_public_publish'
  and publish_state in ('publish_ready','published')
  and image_status = 'approved'
  and risk_level <> 'blocked';

insert into amazon_offer_inventory (
  slug, title, category, amazon_query, store_id_tag_ref, risk_level, approval_state, publish_state,
  offers_path, go_path, last_checked, generated_original_fallback_asset, best_for, buyer_criteria,
  risk_notes, source_attribution, score, confidence, scoring_inputs, missing_data, false_positive_risks
)
select
  v.slug,
  v.title,
  v.category,
  v.amazon_query,
  v.store_id_tag_ref,
  v.risk_level,
  v.approval_state,
  v.publish_state,
  v.offers_path,
  v.go_path,
  v.last_checked::date,
  v.payload->'fallback_asset',
  array(select jsonb_array_elements_text(v.payload->'best_for')),
  v.payload->>'buyer_criteria',
  v.payload->>'risk_notes',
  v.payload->'source_attribution',
  (v.payload->>'score')::numeric,
  (v.payload->>'confidence')::numeric,
  v.payload->'scoring_inputs',
  array(select jsonb_array_elements_text(v.payload->'missing_data')),
  array(select jsonb_array_elements_text(v.payload->'false_positive_risk'))
from (values
  ('ai-meeting-recorder-note-taker', 'AI meeting recorder note taker', 'ai-recorders', 'AI meeting recorder note taker', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/ai-meeting-recorder-note-taker', '/go/ai-meeting-recorder-note-taker', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 1, "slug": "ai-meeting-recorder-note-taker", "title": "AI meeting recorder note taker", "category": "ai-recorders", "amazon_query": "AI meeting recorder note taker", "amazon_search_url": "https://www.amazon.com/s?k=AI+meeting+recorder+note+taker&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of ai meeting recorder note taker for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/2563eb/ffffff?text=SPG+ai+recorders"}, "best_for": ["remote meetings", "founders", "sales calls"], "buyer_criteria": "records meetings and produces searchable summaries", "risk_level": "medium", "risk_notes": "privacy expectations vary by meeting jurisdiction; no claim of consent compliance", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/ai-meeting-recorder-note-taker", "go_path": "/go/ai-meeting-recorder-note-taker", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "ai-recorders"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('ai-voice-recorder-for-interviews', 'AI voice recorder for interviews', 'ai-recorders', 'AI voice recorder for interviews', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/ai-voice-recorder-for-interviews', '/go/ai-voice-recorder-for-interviews', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 2, "slug": "ai-voice-recorder-for-interviews", "title": "AI voice recorder for interviews", "category": "ai-recorders", "amazon_query": "AI voice recorder for interviews", "amazon_search_url": "https://www.amazon.com/s?k=AI+voice+recorder+for+interviews&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of ai voice recorder for interviews for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/059669/ffffff?text=SPG+ai+recorders"}, "best_for": ["journalists", "recruiters", "students"], "buyer_criteria": "captures long conversations for later notes", "risk_level": "medium", "risk_notes": "recording consent rules and noisy search results", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/ai-voice-recorder-for-interviews", "go_path": "/go/ai-voice-recorder-for-interviews", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "ai-recorders"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('e-ink-digital-notebook', 'E-ink digital notebook', 'digital-notebooks', 'e ink digital notebook', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/e-ink-digital-notebook', '/go/e-ink-digital-notebook', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 3, "slug": "e-ink-digital-notebook", "title": "E-ink digital notebook", "category": "digital-notebooks", "amazon_query": "e ink digital notebook", "amazon_search_url": "https://www.amazon.com/s?k=e+ink+digital+notebook&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of e-ink digital notebook for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/dc2626/ffffff?text=SPG+digital+notebooks"}, "best_for": ["students", "executives", "handwriting-first planners"], "buyer_criteria": "paper-like writing without paper clutter", "risk_level": "low", "risk_notes": "model feature drift and incompatible accessories", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/e-ink-digital-notebook", "go_path": "/go/e-ink-digital-notebook", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "digital-notebooks"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('smart-reusable-notebook', 'Smart reusable notebook', 'digital-notebooks', 'smart reusable notebook', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/smart-reusable-notebook', '/go/smart-reusable-notebook', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 4, "slug": "smart-reusable-notebook", "title": "Smart reusable notebook", "category": "digital-notebooks", "amazon_query": "smart reusable notebook", "amazon_search_url": "https://www.amazon.com/s?k=smart+reusable+notebook&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of smart reusable notebook for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/f97316/ffffff?text=SPG+digital+notebooks"}, "best_for": ["budget students", "list-makers", "teachers"], "buyer_criteria": "scan notes then wipe/reuse pages", "risk_level": "low", "risk_notes": "search results may mix notebooks and replacement accessories", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/smart-reusable-notebook", "go_path": "/go/smart-reusable-notebook", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "digital-notebooks"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('usb-c-podcast-microphone', 'USB-C podcast microphone', 'usb-mics', 'USB C podcast microphone', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/usb-c-podcast-microphone', '/go/usb-c-podcast-microphone', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 5, "slug": "usb-c-podcast-microphone", "title": "USB-C podcast microphone", "category": "usb-mics", "amazon_query": "USB C podcast microphone", "amazon_search_url": "https://www.amazon.com/s?k=USB+C+podcast+microphone&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of usb-c podcast microphone for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0f766e/ffffff?text=SPG+usb+mics"}, "best_for": ["podcasters", "streamers", "course creators"], "buyer_criteria": "simple plug-in mic for cleaner voice capture", "risk_level": "low", "risk_notes": "audio quality varies by environment and device", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/usb-c-podcast-microphone", "go_path": "/go/usb-c-podcast-microphone", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "usb-mics"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('compact-usb-condenser-mic', 'Compact USB condenser mic', 'usb-mics', 'compact USB condenser microphone', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/compact-usb-condenser-mic', '/go/compact-usb-condenser-mic', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 6, "slug": "compact-usb-condenser-mic", "title": "Compact USB condenser mic", "category": "usb-mics", "amazon_query": "compact USB condenser microphone", "amazon_search_url": "https://www.amazon.com/s?k=compact+USB+condenser+microphone&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of compact usb condenser mic for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/9333ea/ffffff?text=SPG+usb+mics"}, "best_for": ["Zoom calls", "voiceover beginners", "desk setups"], "buyer_criteria": "small desk mic without XLR gear", "risk_level": "low", "risk_notes": "search results can include bundles and arms", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/compact-usb-condenser-mic", "go_path": "/go/compact-usb-condenser-mic", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "usb-mics"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('portable-power-station-300w', 'Portable power station 300W', 'portable-power-stations', 'portable power station 300W', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/portable-power-station-300w', '/go/portable-power-station-300w', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 7, "slug": "portable-power-station-300w", "title": "Portable power station 300W", "category": "portable-power-stations", "amazon_query": "portable power station 300W", "amazon_search_url": "https://www.amazon.com/s?k=portable+power+station+300W&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of portable power station 300w for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0ea5e9/ffffff?text=SPG+portable+power+stations"}, "best_for": ["camping", "apartments", "storm prep"], "buyer_criteria": "backup power for phones, laptops, small gear", "risk_level": "medium", "risk_notes": "capacity/runtime claims must be verified on Amazon", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/portable-power-station-300w", "go_path": "/go/portable-power-station-300w", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "portable-power-stations"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('portable-power-station-1000w', 'Portable power station 1000W', 'portable-power-stations', 'portable power station 1000W', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/portable-power-station-1000w', '/go/portable-power-station-1000w', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 8, "slug": "portable-power-station-1000w", "title": "Portable power station 1000W", "category": "portable-power-stations", "amazon_query": "portable power station 1000W", "amazon_search_url": "https://www.amazon.com/s?k=portable+power+station+1000W&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of portable power station 1000w for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/7c3aed/ffffff?text=SPG+portable+power+stations"}, "best_for": ["RV trips", "outages", "creators on location"], "buyer_criteria": "larger battery capacity for bigger loads", "risk_level": "medium", "risk_notes": "hazmat/shipping constraints and model changes", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/portable-power-station-1000w", "go_path": "/go/portable-power-station-1000w", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "portable-power-stations"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('folding-solar-panel-kit', 'Folding solar panel kit', 'solar-kits', 'folding solar panel kit portable power station', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/folding-solar-panel-kit', '/go/folding-solar-panel-kit', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 9, "slug": "folding-solar-panel-kit", "title": "Folding solar panel kit", "category": "solar-kits", "amazon_query": "folding solar panel kit portable power station", "amazon_search_url": "https://www.amazon.com/s?k=folding+solar+panel+kit+portable+power+station&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of folding solar panel kit for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/2563eb/ffffff?text=SPG+solar+kits"}, "best_for": ["campers", "emergency kits", "off-grid weekends"], "buyer_criteria": "portable panel to recharge power stations", "risk_level": "medium", "risk_notes": "compatibility varies by connector and wattage", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/folding-solar-panel-kit", "go_path": "/go/folding-solar-panel-kit", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "solar-kits"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('balcony-solar-starter-kit', 'Balcony solar starter kit', 'solar-kits', 'balcony solar starter kit', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/balcony-solar-starter-kit', '/go/balcony-solar-starter-kit', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 10, "slug": "balcony-solar-starter-kit", "title": "Balcony solar starter kit", "category": "solar-kits", "amazon_query": "balcony solar starter kit", "amazon_search_url": "https://www.amazon.com/s?k=balcony+solar+starter+kit&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of balcony solar starter kit for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/059669/ffffff?text=SPG+solar+kits"}, "best_for": ["renters", "apartments", "small patios"], "buyer_criteria": "small solar learning/starter setup", "risk_level": "medium", "risk_notes": "local electrical codes and installation requirements", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/balcony-solar-starter-kit", "go_path": "/go/balcony-solar-starter-kit", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "solar-kits"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('hepa-air-purifier-bedroom', 'HEPA air purifier for bedroom', 'air-purifiers', 'HEPA air purifier bedroom', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/hepa-air-purifier-bedroom', '/go/hepa-air-purifier-bedroom', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 11, "slug": "hepa-air-purifier-bedroom", "title": "HEPA air purifier for bedroom", "category": "air-purifiers", "amazon_query": "HEPA air purifier bedroom", "amazon_search_url": "https://www.amazon.com/s?k=HEPA+air+purifier+bedroom&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of hepa air purifier for bedroom for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/dc2626/ffffff?text=SPG+air+purifiers"}, "best_for": ["allergy sufferers", "bedrooms", "nurseries"], "buyer_criteria": "quiet room air cleaning category", "risk_level": "medium", "risk_notes": "filter costs/CADR/noise require merchant verification", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/hepa-air-purifier-bedroom", "go_path": "/go/hepa-air-purifier-bedroom", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "air-purifiers"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('large-room-air-purifier', 'Large-room air purifier', 'air-purifiers', 'large room air purifier HEPA', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/large-room-air-purifier', '/go/large-room-air-purifier', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 12, "slug": "large-room-air-purifier", "title": "Large-room air purifier", "category": "air-purifiers", "amazon_query": "large room air purifier HEPA", "amazon_search_url": "https://www.amazon.com/s?k=large+room+air+purifier+HEPA&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of large-room air purifier for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/f97316/ffffff?text=SPG+air+purifiers"}, "best_for": ["open living rooms", "pet homes", "smoke season"], "buyer_criteria": "bigger coverage air purifier category", "risk_level": "medium", "risk_notes": "coverage claims vary by brand and test method", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/large-room-air-purifier", "go_path": "/go/large-room-air-purifier", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "air-purifiers"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('under-desk-walking-pad', 'Under-desk walking pad', 'walking-pads', 'under desk walking pad', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/under-desk-walking-pad', '/go/under-desk-walking-pad', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 13, "slug": "under-desk-walking-pad", "title": "Under-desk walking pad", "category": "walking-pads", "amazon_query": "under desk walking pad", "amazon_search_url": "https://www.amazon.com/s?k=under+desk+walking+pad&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of under-desk walking pad for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0f766e/ffffff?text=SPG+walking+pads"}, "best_for": ["remote workers", "low-impact steps", "small apartments"], "buyer_criteria": "walk while working without a full treadmill", "risk_level": "medium", "risk_notes": "noise, return logistics, and weight limits vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/under-desk-walking-pad", "go_path": "/go/under-desk-walking-pad", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "walking-pads"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('folding-walking-pad-with-handle', 'Folding walking pad with handle', 'walking-pads', 'folding walking pad with handle', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/folding-walking-pad-with-handle', '/go/folding-walking-pad-with-handle', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 14, "slug": "folding-walking-pad-with-handle", "title": "Folding walking pad with handle", "category": "walking-pads", "amazon_query": "folding walking pad with handle", "amazon_search_url": "https://www.amazon.com/s?k=folding+walking+pad+with+handle&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of folding walking pad with handle for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/9333ea/ffffff?text=SPG+walking+pads"}, "best_for": ["small apartments", "beginner fitness", "standing desks"], "buyer_criteria": "compact treadmill with more stability", "risk_level": "medium", "risk_notes": "search can include unsafe/low-quality variants", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/folding-walking-pad-with-handle", "go_path": "/go/folding-walking-pad-with-handle", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "walking-pads"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('self-emptying-robot-vacuum', 'Self-emptying robot vacuum', 'robot-vacuums', 'self emptying robot vacuum', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/self-emptying-robot-vacuum', '/go/self-emptying-robot-vacuum', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 15, "slug": "self-emptying-robot-vacuum", "title": "Self-emptying robot vacuum", "category": "robot-vacuums", "amazon_query": "self emptying robot vacuum", "amazon_search_url": "https://www.amazon.com/s?k=self+emptying+robot+vacuum&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of self-emptying robot vacuum for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0ea5e9/ffffff?text=SPG+robot+vacuums"}, "best_for": ["busy households", "pet owners", "hard floors"], "buyer_criteria": "robot vacuum with lower-maintenance dock", "risk_level": "medium", "risk_notes": "floor type and obstacle performance vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/self-emptying-robot-vacuum", "go_path": "/go/self-emptying-robot-vacuum", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "robot-vacuums"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('robot-vacuum-mop-combo', 'Robot vacuum mop combo', 'robot-vacuums', 'robot vacuum mop combo', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/robot-vacuum-mop-combo', '/go/robot-vacuum-mop-combo', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 16, "slug": "robot-vacuum-mop-combo", "title": "Robot vacuum mop combo", "category": "robot-vacuums", "amazon_query": "robot vacuum mop combo", "amazon_search_url": "https://www.amazon.com/s?k=robot+vacuum+mop+combo&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of robot vacuum mop combo for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/7c3aed/ffffff?text=SPG+robot+vacuums"}, "best_for": ["apartments", "pet hair", "tile/hardwood homes"], "buyer_criteria": "single gadget for vacuum plus light mopping", "risk_level": "medium", "risk_notes": "water tank and carpet behavior differs by model", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/robot-vacuum-mop-combo", "go_path": "/go/robot-vacuum-mop-combo", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "robot-vacuums"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('gps-pet-tracker-collar', 'GPS pet tracker collar', 'pet-tech', 'GPS pet tracker collar', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/gps-pet-tracker-collar', '/go/gps-pet-tracker-collar', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 17, "slug": "gps-pet-tracker-collar", "title": "GPS pet tracker collar", "category": "pet-tech", "amazon_query": "GPS pet tracker collar", "amazon_search_url": "https://www.amazon.com/s?k=GPS+pet+tracker+collar&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of gps pet tracker collar for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/2563eb/ffffff?text=SPG+pet+tech"}, "best_for": ["dog owners", "escape artists", "travelers"], "buyer_criteria": "location category for pet safety workflows", "risk_level": "medium", "risk_notes": "subscription requirements and coverage vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/gps-pet-tracker-collar", "go_path": "/go/gps-pet-tracker-collar", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "pet-tech"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('automatic-pet-feeder-camera', 'Automatic pet feeder with camera', 'pet-tech', 'automatic pet feeder camera', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/automatic-pet-feeder-camera', '/go/automatic-pet-feeder-camera', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 18, "slug": "automatic-pet-feeder-camera", "title": "Automatic pet feeder with camera", "category": "pet-tech", "amazon_query": "automatic pet feeder camera", "amazon_search_url": "https://www.amazon.com/s?k=automatic+pet+feeder+camera&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of automatic pet feeder with camera for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/059669/ffffff?text=SPG+pet+tech"}, "best_for": ["busy pet owners", "cats", "small dogs"], "buyer_criteria": "scheduled feeding with remote visibility", "risk_level": "medium", "risk_notes": "app reliability/privacy and portion accuracy vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/automatic-pet-feeder-camera", "go_path": "/go/automatic-pet-feeder-camera", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "pet-tech"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('travel-esim-phone-plan', 'Travel eSIM phone plan', 'travel-tech', 'travel eSIM phone plan', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/travel-esim-phone-plan', '/go/travel-esim-phone-plan', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 19, "slug": "travel-esim-phone-plan", "title": "Travel eSIM phone plan", "category": "travel-tech", "amazon_query": "travel eSIM phone plan", "amazon_search_url": "https://www.amazon.com/s?k=travel+eSIM+phone+plan&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of travel esim phone plan for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/dc2626/ffffff?text=SPG+travel+tech"}, "best_for": ["international travelers", "digital nomads", "family trips"], "buyer_criteria": "connectivity prep without swapping physical SIMs", "risk_level": "low", "risk_notes": "Amazon may surface guides/accessories rather than plans", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/travel-esim-phone-plan", "go_path": "/go/travel-esim-phone-plan", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "travel-tech"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('portable-luggage-scale', 'Portable luggage scale', 'travel-tech', 'portable luggage scale digital', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/portable-luggage-scale', '/go/portable-luggage-scale', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 20, "slug": "portable-luggage-scale", "title": "Portable luggage scale", "category": "travel-tech", "amazon_query": "portable luggage scale digital", "amazon_search_url": "https://www.amazon.com/s?k=portable+luggage+scale+digital&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of portable luggage scale for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/f97316/ffffff?text=SPG+travel+tech"}, "best_for": ["frequent flyers", "families", "carry-on optimizers"], "buyer_criteria": "avoid overweight bag surprises", "risk_level": "low", "risk_notes": "battery/display accuracy varies by SKU", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/portable-luggage-scale", "go_path": "/go/portable-luggage-scale", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "travel-tech"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('red-light-therapy-panel', 'Red light therapy panel', 'wellness-recovery', 'red light therapy panel', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/red-light-therapy-panel', '/go/red-light-therapy-panel', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 21, "slug": "red-light-therapy-panel", "title": "Red light therapy panel", "category": "wellness-recovery", "amazon_query": "red light therapy panel", "amazon_search_url": "https://www.amazon.com/s?k=red+light+therapy+panel&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of red light therapy panel for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0f766e/ffffff?text=SPG+wellness+recovery"}, "best_for": ["recovery routines", "desk workers", "wellness shoppers"], "buyer_criteria": "at-home red-light wellness gadget category", "risk_level": "medium", "risk_notes": "medical/therapeutic claims must be avoided", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/red-light-therapy-panel", "go_path": "/go/red-light-therapy-panel", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "wellness-recovery"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('massage-gun-recovery-tool', 'Massage gun recovery tool', 'wellness-recovery', 'massage gun recovery tool', 'mehyarmedia-20', 'medium', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/massage-gun-recovery-tool', '/go/massage-gun-recovery-tool', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 22, "slug": "massage-gun-recovery-tool", "title": "Massage gun recovery tool", "category": "wellness-recovery", "amazon_query": "massage gun recovery tool", "amazon_search_url": "https://www.amazon.com/s?k=massage+gun+recovery+tool&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of massage gun recovery tool for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/9333ea/ffffff?text=SPG+wellness+recovery"}, "best_for": ["gym users", "runners", "sore desk workers"], "buyer_criteria": "percussive recovery category for general comfort", "risk_level": "medium", "risk_notes": "health claims and battery quality vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/massage-gun-recovery-tool", "go_path": "/go/massage-gun-recovery-tool", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 82, "confidence": 0.78, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "medium", "category_coverage": "wellness-recovery"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('ergonomic-monitor-arm', 'Ergonomic monitor arm', 'desk-gear', 'ergonomic monitor arm', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/ergonomic-monitor-arm', '/go/ergonomic-monitor-arm', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 23, "slug": "ergonomic-monitor-arm", "title": "Ergonomic monitor arm", "category": "desk-gear", "amazon_query": "ergonomic monitor arm", "amazon_search_url": "https://www.amazon.com/s?k=ergonomic+monitor+arm&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of ergonomic monitor arm for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/0ea5e9/ffffff?text=SPG+desk+gear"}, "best_for": ["home offices", "dual-screen workers", "small desks"], "buyer_criteria": "clear desk space and raise screen height", "risk_level": "low", "risk_notes": "VESA/desk thickness compatibility risk", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/ergonomic-monitor-arm", "go_path": "/go/ergonomic-monitor-arm", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "desk-gear"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('desk-cable-management-kit', 'Desk cable management kit', 'desk-gear', 'desk cable management kit', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/desk-cable-management-kit', '/go/desk-cable-management-kit', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 24, "slug": "desk-cable-management-kit", "title": "Desk cable management kit", "category": "desk-gear", "amazon_query": "desk cable management kit", "amazon_search_url": "https://www.amazon.com/s?k=desk+cable+management+kit&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of desk cable management kit for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/7c3aed/ffffff?text=SPG+desk+gear"}, "best_for": ["standing desks", "gaming setups", "offices"], "buyer_criteria": "low-cost cleanup for cable chaos", "risk_level": "low", "risk_notes": "adhesive quality and kit contents vary", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/desk-cable-management-kit", "go_path": "/go/desk-cable-management-kit", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "desk-gear"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb),
  ('glass-meal-prep-containers', 'Glass meal prep containers', 'meal-prep', 'glass meal prep containers', 'mehyarmedia-20', 'low', 'data_seed_ready_compliance_review_required', 'hold_for_webdev_generation_and_compliance_gate', '/offers/glass-meal-prep-containers', '/go/glass-meal-prep-containers', '2026-05-16T18:18:46Z'::timestamptz, '{"rank": 25, "slug": "glass-meal-prep-containers", "title": "Glass meal prep containers", "category": "meal-prep", "amazon_query": "glass meal prep containers", "amazon_search_url": "https://www.amazon.com/s?k=glass+meal+prep+containers&tag=mehyarmedia-20", "store_id_tag_ref": "mehyarmedia-20", "image": {"image_url": null, "source": "none_selected_amazon_images_prohibited_until_rights_approved", "license": "not_applicable", "status": "needs_owned_or_generated_asset", "rights_notes": "Do not use Amazon product images unless obtained through approved Amazon Associates tooling/API permissions; use generated/original fallback asset first."}, "fallback_asset": {"type": "generated_or_original_spg_asset", "asset_prompt": "Original editorial illustration of glass meal prep containers for StuffPrettyGood buyer guide, no brand logos, no product-identical rendering.", "placeholder_url": "https://placehold.co/1200x800/2563eb/ffffff?text=SPG+meal+prep"}, "best_for": ["meal preppers", "families", "office lunches"], "buyer_criteria": "durable food storage starter category", "risk_level": "low", "risk_notes": "lid fit, oven/freezer limits vary by product", "last_checked": "2026-05-16", "approval_state": "data_seed_ready_compliance_review_required", "publish_state": "hold_for_webdev_generation_and_compliance_gate", "offers_path": "/offers/glass-meal-prep-containers", "go_path": "/go/glass-meal-prep-containers", "click_counters": {"click_count": 0, "signup_count": 0, "last_rollup_at": null, "raw_pii_stored": false}, "source_attribution": {"source_type": "manual_amazon_search_seed", "source_name": "DataEng Amazon-first top-25 seed set", "source_url": "https://www.amazon.com/s", "source_license": "metadata/original-summary only; no copied Amazon creative", "retrieved_at": "2026-05-16T18:18:46Z", "refresh_cadence": "weekly manual link/right/status review; daily click counter rollup after /go instrumentation is live"}, "score": 88, "confidence": 0.84, "scoring_inputs": {"buyer_intent": "high", "amazon_fit": "high", "content_monetization_fit": "high", "rights_readiness": "fallback_asset_required", "risk_penalty": "low", "category_coverage": "meal-prep"}, "missing_data": ["approved original/generated image asset", "live redirect health check", "ComplyOps public-publish approval"], "false_positive_risk": ["Amazon search result may surface irrelevant or low-quality products", "merchant terms/tag handling may change", "category demand may be seasonal/noisy"]}'::jsonb)
) as v(slug, title, category, amazon_query, store_id_tag_ref, risk_level, approval_state, publish_state, offers_path, go_path, last_checked, payload)
on conflict (slug) do update set
  title = excluded.title,
  category = excluded.category,
  amazon_query = excluded.amazon_query,
  store_id_tag_ref = excluded.store_id_tag_ref,
  risk_level = excluded.risk_level,
  approval_state = excluded.approval_state,
  publish_state = excluded.publish_state,
  offers_path = excluded.offers_path,
  go_path = excluded.go_path,
  last_checked = excluded.last_checked,
  generated_original_fallback_asset = excluded.generated_original_fallback_asset,
  best_for = excluded.best_for,
  buyer_criteria = excluded.buyer_criteria,
  risk_notes = excluded.risk_notes,
  source_attribution = excluded.source_attribution,
  score = excluded.score,
  confidence = excluded.confidence,
  scoring_inputs = excluded.scoring_inputs,
  missing_data = excluded.missing_data,
  false_positive_risks = excluded.false_positive_risks,
  updated_at = now();
