
import fs from 'fs';import path from 'path';
const root=process.cwd(), dist=path.join(root,'dist');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(dist,{recursive:true});
const data=JSON.parse(fs.readFileSync('data/products.json','utf8'));const posts=JSON.parse(fs.readFileSync('data/posts.json','utf8')).posts;const products=data.products.filter(p=>p.affiliate_status==='approved'&&p.affiliate_url&&p.affiliate_url.includes('tag=mehyarmedia-20'));
fs.mkdirSync(path.join(dist,'assets/products'),{recursive:true});fs.copyFileSync('src/styles.css',path.join(dist,'styles.css'));
for(const p of products){const svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 420"><defs><linearGradient id="g" x1="0" x2="1"><stop stop-color="#ffe1ba"/><stop offset="1" stop-color="#d8fae8"/></linearGradient></defs><rect width="640" height="420" fill="url(#g)"/><circle cx="520" cy="80" r="90" fill="#fff6"/><text x="42" y="190" font-family="Arial" font-size="34" font-weight="800" fill="#17130d">${esc(p.category).toUpperCase()}</text><text x="42" y="242" font-family="Arial" font-size="24" fill="#5f5447">Stuff Pretty Good</text></svg>`;fs.writeFileSync(path.join(dist,p.image_url),svg)}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function layout(title,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} | Stuff Pretty Good</title><meta name="description" content="AI-assisted shopping guide using affiliate-approved products only."><link rel="stylesheet" href="/styles.css"></head><body><div class="wrap"><nav class="nav"><a class="logo" href="/">Stuff Pretty Good</a><div><a class="pill" href="/gift-finder/">Gift Finder</a> <a class="pill" href="/starter-kits/">Starter Kits</a> <a class="pill" href="/under-50/">Under $50</a></div></nav>${body}<footer class="footer"><a href="/affiliate-disclosure/">Affiliate Disclosure</a><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/contact/">Contact</a><a href="/unsubscribe/">Unsubscribe</a><a href="/preferences/">Preferences</a></footer></div></body></html>`}
function card(p){return `<article class="card"><a class="thumb" href="/products/${p.id}/"><img src="${p.image_url}" alt=""></a><div class="tag">${esc(p.price_band)} · approved</div><h3>${esc(p.title)}</h3><p>${esc(p.why_useful)}</p><p><strong>Best for:</strong> ${esc(p.best_for)}</p><a class="btn" href="/products/${p.id}/">See why</a></article>`}
function mkdirPage(route,html){const dir=path.join(dist,route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html)}
const hero=`<section class="hero"><div><div class="eyebrow">Approved-offer catalog · Amazon first</div><h1>AI finds useful stuff worth buying.</h1><p class="sub">Gifts, starter kits, useful finds, and practical products — filtered by budget and what you actually need. No fake hype. No unapproved outbound links.</p><div class="actions"><a class="btn" href="/gift-finder/">Find a Gift</a><a class="btn alt" href="/starter-kits/">Build a Starter Kit</a><a class="btn alt" href="/under-50/">Find Stuff Under $50</a></div></div><div class="panel"><div class="eyebrow">Hard rule</div><h2>Approved links only.</h2><p>No outbound product link goes live unless it is monetized through an approved affiliate program.</p><div><span class="badge">affiliate_status=approved</span><span class="badge">tag=mehyarmedia-20</span><span class="badge">no scraped Amazon metadata</span></div></div></section>`;
const rails=['under-25','under-50','travel','home-office','kitchen','pets'];
let home=hero+`<section class="section"><h2>Useful finds by budget and need</h2><div class="grid">${products.slice(0,12).map(card).join('')}</div></section><section class="section panel"><h2>First buying guides</h2><p class="sub">Original starter pages built for affiliate approval and real buyer intent.</p>${posts.map(p=>`<p><a class="pill" href="/guides/${p.slug}/">${esc(p.title)}</a></p>`).join('')}</section><p class="notice">Disclosure: Some links are paid links. If you buy through them, Stuff Pretty Good may earn a commission at no extra cost to you. As an Amazon Associate, Stuff Pretty Good earns from qualifying purchases.</p>`;
mkdirPage('',layout('AI-assisted shopping guide',home));
for(const r of rails){mkdirPage(r,layout(r,`<section class="section"><h1>${esc(r.replace('-', ' '))}</h1><p class="sub">Affiliate-approved Amazon finds only.</p><div class="grid">${products.filter(p=>p.price_band===r||p.category===r).concat(products.slice(0,4)).slice(0,12).map(card).join('')}</div></section>`))}
for(const p of products){mkdirPage(`products/${p.id}`,layout(p.title,`<article class="post"><div class="tag">${esc(p.category)} · ${esc(p.price_band)} · approved affiliate link</div><h1>${esc(p.title)}</h1><img class="thumb" src="${p.image_url}" alt=""><p>${esc(p.why_useful)}</p><p><strong>Best for:</strong> ${esc(p.best_for)}</p><p><strong>Avoid if:</strong> ${esc(p.avoid_if)}</p><a class="btn" href="/go/${p.id}/" rel="nofollow sponsored">View on Amazon</a><p class="notice">As an Amazon Associate, Stuff Pretty Good earns from qualifying purchases.</p></article>`));mkdirPage(`go/${p.id}`,`<!doctype html><meta charset="utf-8"><title>Redirecting</title><meta name="robots" content="noindex"><link rel="canonical" href="${p.affiliate_url}"><p>Redirecting to approved merchant…</p><script>location.replace(${JSON.stringify(p.affiliate_url)})</script><p><a href="${p.affiliate_url}" rel="nofollow sponsored">Continue</a></p>`)}
for(const post of posts){const picks=products.filter(p=>p.category===post.category||p.price_band===post.category).concat(products).slice(0,8);mkdirPage(`guides/${post.slug}`,layout(post.title,`<article class="post"><h1>${esc(post.title)}</h1><p class="sub">${esc(post.intro)}</p><ol>${picks.map(p=>`<li><strong>${esc(p.title)}</strong><br>Why useful: ${esc(p.why_useful)}<br>Best for: ${esc(p.best_for)}<br>Avoid if: ${esc(p.avoid_if)}<br><a href="/products/${p.id}/">Read the pick</a></li>`).join('')}</ol><p class="notice">Disclosure: Some links are paid links. As an Amazon Associate, Stuff Pretty Good earns from qualifying purchases.</p></article>`))}
const toolPage=(name,desc)=>layout(name,`<section class="section panel"><div class="eyebrow">v0.1 catalog-safe AI tool</div><h1>${name}</h1><p class="sub">${desc}</p><form class="finder"><input class="input" placeholder="Who / what for?"><input class="input" placeholder="Budget"><input class="input" placeholder="Interests"><button class="btn" type="button">Search approved catalog</button></form><p class="notice">v0.1 uses approved catalog records only; AI must not invent products.</p></section><section class="section"><h2>Starter picks</h2><div class="grid">${products.slice(0,8).map(card).join('')}</div></section>`);
mkdirPage('gift-finder',toolPage('AI Gift Finder','Answer a few prompts and get gift ideas from the approved-offer catalog only.'));
mkdirPage('starter-kits',toolPage('AI Starter Kit Builder','Build useful setups from approved affiliate products only.'));
mkdirPage('useful-finds',toolPage('Useful Finds','Browse practical picks that solve daily annoyances.'));
const pages={about:'Stuff Pretty Good is an AI-assisted shopping guide for useful products, gifts, and starter kits.',advertise:'Partner with Stuff Pretty Good through approved placements and compliant affiliate programs only.','affiliate-disclosure':'Disclosure: Some links are paid links. If you buy through them, Stuff Pretty Good may earn a commission at no extra cost to you. As an Amazon Associate, Stuff Pretty Good earns from qualifying purchases.',privacy:'We collect only what is needed for preferences, subscriptions, recommendations, and analytics.',terms:'Use Stuff Pretty Good lawfully. Product availability and merchant terms are controlled by merchants.',contact:'Contact: hello@mehyar.us',unsubscribe:'Unsubscribe center placeholder for email compliance.',preferences:'Choose interests: gifts, home, tech, travel, pets, kitchen, useful deals under $50.'};
for(const [slug,txt] of Object.entries(pages)) mkdirPage(slug,layout(slug,`<section class="section post"><h1>${esc(slug.replaceAll('-',' '))}</h1><p class="sub">${esc(txt)}</p></section>`));
fs.writeFileSync(path.join(dist,'robots.txt'),'User-agent: *\nAllow: /\nSitemap: https://stuffprettygood.com/sitemap.xml\n');
const urls=['','gift-finder','starter-kits','under-25','under-50',...posts.map(p=>'guides/'+p.slug),...products.map(p=>'products/'+p.id)];fs.writeFileSync(path.join(dist,'sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${urls.map(u=>`<url><loc>https://stuffprettygood.com/${u?u+'/':''}</loc></url>`).join('')}</urlset>`);
console.log(`built ${products.length} approved products, ${posts.length} guides`);
